/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
        tools {
            maven 'maven'
        }
    stages {
        stage('test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}