/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
        tools {
            maven 'Maven 3.3.9'
            jdk 'jdk17'
        }
    stages {
        stage('test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}